src/Entity/Profil.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfilRepository")
 */
class Profil
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="integer")
     */
    private $taille;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $poid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $couleur_yeux;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $couleur_cheveux;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $citation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $livres;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cinema;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $loisir;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $langue_parle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $activite_prefere;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getTaille(): ?int
    {
        return $this->taille;
    }

    public function setTaille(int $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getPoid(): ?int
    {
        return $this->poid;
    }

    public function setPoid(?int $poid): self
    {
        $this->poid = $poid;

        return $this;
    }

    public function getCouleurYeux(): ?string
    {
        return $this->couleur_yeux;
    }

    public function setCouleurYeux(string $couleur_yeux): self
    {
        $this->couleur_yeux = $couleur_yeux;

        return $this;
    }

    public function getCouleurCheveux(): ?string
    {
        return $this->couleur_cheveux;
    }

    public function setCouleurCheveux(string $couleur_cheveux): self
    {
        $this->couleur_cheveux = $couleur_cheveux;

        return $this;
    }

    public function getCitation(): ?string
    {
        return $this->citation;
    }

    public function setCitation(?string $citation): self
    {
        $this->citation = $citation;

        return $this;
    }

    public function getLivres(): ?string
    {
        return $this->livres;
    }

    public function setLivres(string $livres): self
    {
        $this->livres = $livres;

        return $this;
    }

    public function getCinema(): ?string
    {
        return $this->cinema;
    }

    public function setCinema(string $cinema): self
    {
        $this->cinema = $cinema;

        return $this;
    }

    public function getLoisir(): ?string
    {
        return $this->loisir;
    }

    public function setLoisir(string $loisir): self
    {
        $this->loisir = $loisir;

        return $this;
    }

    public function getLangueParle(): ?string
    {
        return $this->langue_parle;
    }

    public function setLangueParle(string $langue_parle): self
    {
        $this->langue_parle = $langue_parle;

        return $this;
    }

    public function getActivitePrefere(): ?string
    {
        return $this->activite_prefere;
    }

    public function setActivitePrefere(string $activite_prefere): self
    {
        $this->activite_prefere = $activite_prefere;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Form/ProfilType.php
<?php

namespace App\Form;

use App\Entity\Profil;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('age')
            ->add('taille')
            ->add('poid')
            ->add('couleur_yeux')
            ->add('couleur_cheveux')
            ->add('citation')
            ->add('livres')
            ->add('cinema')
            ->add('loisir')
            ->add('langue_parle')
            ->add('activite_prefere')
            ->add('photo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Profil::class,
        ]);
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Profil;
use App\Form\ProfilType;
use App\Repository\ProfilRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/profil")
 */
class ProfilController extends AbstractController
{
    /**
     * @Route("/", name="profil_index", methods={"GET"})
     */
    public function index(ProfilRepository $profilRepository, SessionInterface $session): Response
    {
        $session->set('foo', 'bar');

        // gets the attribute set by another controller in another request
        $foobar = $session->get('foobar');

        // uses a default value if the attribute doesn't exist
        $filters = $session->get('filters', []);


        return $this->render('profil/index.html.twig', [
            'profils' => $profilRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="profil_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $profil = new Profil();

        $form = $this->createForm(ProfilType::class, $profil);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($profil);
            $entityManager->flush();
            $this->addFlash(
                'notice',
                'Vous avez créé votre profil!'
            );



            return $this->redirectToRoute('profil_index');
        }



        return $this->render('profil/new.html.twig', [
            'profil' => $profil,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="profil_show", methods={"GET"})
     */
    public function show(Profil $profil): Response
    {
        return $this->render('profil/show.html.twig', [
            'profil' => $profil,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="profil_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Profil $profil): Response
    {
        $form = $this->createForm(ProfilType::class, $profil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash(
                'notice',
                'Votre profil a bien été modifié!'
            );

            return $this->redirectToRoute('profil_index');
        }

        return $this->render('profil/edit.html.twig', [
            'profil' => $profil,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="profil_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Profil $profil): Response
    {
        if ($this->isCsrfTokenValid('delete'.$profil->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($profil);
            $entityManager->flush();
            $this->addFlash(
                'notice',
                'Votre profil a été supprimé'
            );
        }

        return $this->redirectToRoute('profil_index');
    }
}

templates/profil/_delete_form.html.twig
<form method="post" action="{{ path('profil_delete', {'id': profil.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profil.id) }}">
    <button class="btn">Delete</button>
</form>

templates/profil/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profil{% endblock %}

{% block body %}
    <h1>Edit Profil</h1>

    {{ include('profil/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('profil_index') }}">back to list</a>

    {{ include('profil/_delete_form.html.twig') }}
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil index{% endblock %}

{% block body %}
    <h1>Profil index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Age</th>
                <th>Taille</th>
                <th>Poid</th>
                <th>Couleur_yeux</th>
                <th>Couleur_cheveux</th>
                <th>Citation</th>
                <th>Livres</th>
                <th>Cinema</th>
                <th>Loisir</th>
                <th>Langue_parle</th>
                <th>Activite_prefere</th>
                <th>Photo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for profil in profils %}
            <tr>
                <td>{{ profil.id }}</td>
                <td>{{ profil.title }}</td>
                <td>{{ profil.description }}</td>
                <td>{{ profil.age }}</td>
                <td>{{ profil.taille }}</td>
                <td>{{ profil.poid }}</td>
                <td>{{ profil.couleurYeux }}</td>
                <td>{{ profil.couleurCheveux }}</td>
                <td>{{ profil.citation }}</td>
                <td>{{ profil.livres }}</td>
                <td>{{ profil.cinema }}</td>
                <td>{{ profil.loisir }}</td>
                <td>{{ profil.langueParle }}</td>
                <td>{{ profil.activitePrefere }}</td>
                <td>{{ profil.photo }}</td>
                <td>
                    <a href="{{ path('profil_show', {'id': profil.id}) }}">show</a>
                    <a href="{{ path('profil_edit', {'id': profil.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="16">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('profil_new') }}">Create new</a>
{% endblock %}

templates/profil/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Profil{% endblock %}

{% block body %}
    <h1>Create new Profil</h1>

    {{ include('profil/_form.html.twig') }}

    <a href="{{ path('profil_index') }}">back to list</a>
{% endblock %}

templates/profil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
    <h1>Profil</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ profil.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ profil.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ profil.description }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ profil.age }}</td>
            </tr>
            <tr>
                <th>Taille</th>
                <td>{{ profil.taille }}</td>
            </tr>
            <tr>
                <th>Poid</th>
                <td>{{ profil.poid }}</td>
            </tr>
            <tr>
                <th>Couleur_yeux</th>
                <td>{{ profil.couleurYeux }}</td>
            </tr>
            <tr>
                <th>Couleur_cheveux</th>
                <td>{{ profil.couleurCheveux }}</td>
            </tr>
            <tr>
                <th>Citation</th>
                <td>{{ profil.citation }}</td>
            </tr>
            <tr>
                <th>Livres</th>
                <td>{{ profil.livres }}</td>
            </tr>
            <tr>
                <th>Cinema</th>
                <td>{{ profil.cinema }}</td>
            </tr>
            <tr>
                <th>Loisir</th>
                <td>{{ profil.loisir }}</td>
            </tr>
            <tr>
                <th>Langue_parle</th>
                <td>{{ profil.langueParle }}</td>
            </tr>
            <tr>
                <th>Activite_prefere</th>
                <td>{{ profil.activitePrefere }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ profil.photo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('profil_index') }}">back to list</a>

    <a href="{{ path('profil_edit', {'id': profil.id}) }}">edit</a>

    {{ include('profil/_delete_form.html.twig') }}
{% endblock %}